// CFR 默认配置
const CFR_DEFAULTS = [
  { k: "stringbuffer", d: "Sugar StringBuffer", t: "bool", v: "false" },
  { k: "stringbuilder", d: "Sugar StringBuilder", t: "bool", v: "true" },
  { k: "stringconcat", d: "Sugar StringConcatFactory", t: "bool", v: "true" },
  { k: "decodeenumswitch", d: "Resugar Enum Switch", t: "bool", v: "true" },
  { k: "sugarenums", d: "Resugar Enums", t: "bool", v: "true" },
  { k: "decodestringswitch", d: "Resugar String Switch", t: "bool", v: "true" },
  { k: "previewfeatures", d: "Preview Features", t: "bool", v: "true" },
  { k: "sealed", d: "Sealed Classes", t: "bool", v: "true" },
  { k: "switchexpression", d: "Switch Expression", t: "bool", v: "true" },
  { k: "recordtypes", d: "Record Types", t: "bool", v: "true" },
  { k: "instanceofpattern", d: "Instanceof Pattern", t: "bool", v: "true" },
  { k: "arrayiter", d: "Array Iteration", t: "bool", v: "true" },
  { k: "collectioniter", d: "Collection Iteration", t: "bool", v: "true" },
  { k: "tryresources", d: "Try-With-Resources", t: "bool", v: "true" },
  { k: "decodelambdas", d: "Decode Lambdas", t: "bool", v: "true" },
  { k: "innerclasses", d: "Inner Classes", t: "bool", v: "true" },
  { k: "forbidmethodscopedclasses", d: "Forbid Method Scoped", t: "bool", v: "false" },
  { k: "forbidanonymousclasses", d: "Forbid Anonymous", t: "bool", v: "false" },
  { k: "skipbatchinnerclasses", d: "Skip Batch Inner", t: "bool", v: "true" },
  { k: "hideutf", d: "Hide UTF8", t: "bool", v: "true" },
  { k: "hidelongstrings", d: "Hide Long Strings", t: "bool", v: "false" },
  { k: "removeboilerplate", d: "Remove Boilerplate", t: "bool", v: "true" },
  { k: "removeinnerclasssynthetics", d: "Remove Inner Synthetics", t: "bool", v: "true" },
  { k: "relinkconst", d: "Relink Constants", t: "bool", v: "true" },
  { k: "liftconstructorinit", d: "Lift Constructor Init", t: "bool", v: "true" },
  { k: "removedeadmethods", d: "Remove Dead Methods", t: "bool", v: "true" },
  { k: "removebadgenerics", d: "Remove Bad Generics", t: "bool", v: "true" },
  { k: "sugarasserts", d: "Sugar Asserts", t: "bool", v: "true" },
  { k: "sugarboxing", d: "Sugar Boxing", t: "bool", v: "true" },
  { k: "sugarretrolambda", d: "Sugar Retro Lambda", t: "bool", v: "false" },
  { k: "showversion", d: "Show CFR Version", t: "bool", v: "false" },
  { k: "decodefinally", d: "Decode Finally", t: "bool", v: "true" },
  { k: "tidymonitors", d: "Tidy Monitors", t: "bool", v: "true" },
  { k: "commentmonitors", d: "Comment Monitors", t: "bool", v: "false" },
  { k: "lenient", d: "Lenient Mode", t: "bool", v: "true" },
  { k: "dumpclasspath", d: "Dump Classpath", t: "bool", v: "false" },
  { k: "comments", d: "Decompiler Comments", t: "bool", v: "false" },
  { k: "ignoreexceptionsalways", d: "Ignore Exceptions Always", t: "bool", v: "false" },
  { k: "antiobf", d: "Anti Obfuscation", t: "bool", v: "false" },
  { k: "obfcontrol", d: "Obfuscated Control Flow", t: "bool", v: "false" },
  { k: "obfattr", d: "Obfuscated Attributes", t: "bool", v: "false" },
  { k: "constobf", d: "Obfuscated Constants", t: "bool", v: "false" },
  { k: "hidebridgemethods", d: "Hide Bridge Methods", t: "bool", v: "true" },
  { k: "ignoreexceptions", d: "Ignore Exceptions", t: "bool", v: "false" },
  { k: "silent", d: "Silent", t: "bool", v: "false" },
  { k: "recover", d: "Recover", t: "bool", v: "true" },
  { k: "eclipse", d: "Eclipse Compat", t: "bool", v: "true" },
  { k: "override", d: "Generate @Override", t: "bool", v: "true" },
  { k: "showinferrable", d: "Show Inferrable Types", t: "bool", v: "false" },
  { k: "allowcorrecting", d: "Allow Correcting", t: "bool", v: "true" },
  { k: "labelledblocks", d: "Labelled Blocks", t: "bool", v: "true" },
  { k: "j14classobj", d: "Java 1.4 Class Objects", t: "bool", v: "false" },
  { k: "hidelangimports", d: "Hide java.lang Imports", t: "bool", v: "false" },
  { k: "staticinitreturn", d: "Static Init Return", t: "bool", v: "true" },
  { k: "usenametable", d: "Use Name Table", t: "bool", v: "true" },
  { k: "pullcodecase", d: "Pull Code Case", t: "bool", v: "false" },
  { k: "elidescala", d: "Elide Scala", t: "bool", v: "false" },
  { k: "usesignatures", d: "Use Signatures", t: "bool", v: "true" },
  { k: "caseinsensitivefs", d: "Case Insensitive FS", t: "bool", v: "false" },
  { k: "lomem", d: "Low Mem", t: "bool", v: "false" },
  { k: "trackbytecodeloc", d: "Track Bytecode Loc", t: "bool", v: "false" },
  { k: "dumpexceptionstacktrace", d: "Dump Exception Stack", t: "bool", v: "true" },

  { k: "forcetopsort", d: "Force Topsort", t: "troolean", v: "neither" },
  { k: "forloopaggcapture", d: "For Loop Agg Capture", t: "troolean", v: "neither" },
  { k: "forcetopsortaggress", d: "Force Topsort Aggress", t: "troolean", v: "neither" },
  { k: "forcetopsortnopull", d: "Force Topsort NoPull", t: "troolean", v: "neither" },
  { k: "forcecondpropagate", d: "Force Cond Propagate", t: "troolean", v: "neither" },
  { k: "reducecondscope", d: "Reduce Cond Scope", t: "troolean", v: "neither" },
  { k: "forcereturningifs", d: "Force Returning Ifs", t: "troolean", v: "neither" },
  { k: "forceexceptionprune", d: "Force Exception Prune", t: "troolean", v: "neither" },
  { k: "aexagg", d: "Aggressive Ex Agg", t: "troolean", v: "neither" },
  { k: "aexagg2", d: "Aggressive Ex Agg 2", t: "troolean", v: "neither" },
  { k: "recovertypeclash", d: "Recover Type Clash", t: "troolean", v: "neither" },
  { k: "recovertypehints", d: "Recover Type Hints", t: "troolean", v: "neither" },
  { k: "removedeadconditionals", d: "Remove Dead Conditionals", t: "troolean", v: "neither" },
  { k: "aggressivedoextension", d: "Aggressive Do Ext", t: "troolean", v: "neither" },
  { k: "aggressiveduff", d: "Aggressive Duff", t: "troolean", v: "neither" },
  { k: "allowmalformedswitch", d: "Allow Malformed Switch", t: "troolean", v: "neither" },
  { k: "clobber", d: "Clobber Files", t: "troolean", v: "neither" },
  
  { k: "decompiletimeout", d: "[Web] Timeout (ms)", t: "int", v: "15000" }
];